### PR TITLE
mention archlinux package

### PR DESCRIPTION
**Pull request by gcb**
thanks for the initiative.

waiting for the v2 tag to update there too. cheers.

### CODE REVIEW

**Comment by Troels51** [comment]
Thanks for the packaging.
Version 1 also included a binary called "tree", that should probably be removed as it isn't useful and shadows the usual tree utility.

Will you update this package when new versions are pushed?

**Comment by gcb** [comment]
i'm not installing `tree` anywhere. it's just left as a build artifact in the build dir/chroot.
The only installed binary is `target/bin/dterm` installed as `bin/dtui`

Yep, for now i'm manually updating it. Subscribed to "releases" updates here. I'm moving my many work github accounts into this one so automation will take a a while.

**Comment by Troels51** [comment]
Good. Ill tag version 2 tonight, then that should get easier.

I am not too familiar with AUR, but as far as I can read packages are built with a PKGBUILD file, would it make things easier if that was out in this repository, so that it gets updated with new versions?

**Comment by gcb** [comment]
You are correct. The PKGBUILD is mostly a small shell script that have some source info and list the build steps, usually using the source repo own helpers (makefile etc).

Good idea about centralizing things, but some PKGBUILD must live in a repo at aur.archlinux.org ...if nothing just to point to this repo and use the actual PKGBUILD from here. If it ever gets more complex than listing dependencies and metadata... but as it is it's fine there with a README mention here.

**Comment by Troels51** [comment]
Alright.

Again thanks for doing the packaging :)

**Comment by Troels51** [comment]
@gcb, v2.0.0 tag has been added so you can update the package

**Comment by Troels51** [comment]
@gcb I updated the tags to v3.0.1, and then also updated the PKGBUILD to fix a couple of issues, and it would be nice if you updated the package :).
I am not sure how to reach out if i have patches, is there a better way that with an @
```
# Maintainer: gcb <1705-gcb@users.noreply.gitlab.archlinux.org>
pkgname=dtui
pkgdesc='Small TUI for introspecting the state of the system/session dbus'
pkgver=3.0.1
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/Troels51/${pkgname}/archive/refs/tags/v${pkgver}.tar.gz")

sha256sums=('611e27a18750630025e29bcf5736d4b8ac57e8bba527c734b05623aecab99ed3')
pkgrel=1
arch=('x86_64')
url=https://github.com/Troels51/dtui
license=('MIT')
depends=()
makedepends=(rust)
optdepends=()

build() {
	cd "$pkgname-$pkgver"
	cargo build --release --verbose --locked
}

check() {
	cd "$pkgname-$pkgver"
	cargo test --release --verbose --locked
}

package() {
	cd "$srcdir/$pkgname-$pkgver"
	install -Dm 0755 target/release/dtui "$pkgdir/usr/bin/dtui"
}
```

**Comment by gcb** [comment]
@Troels51 I'm subscribed to this repo. But it seems I only get notified with there's an actual release (that's what we get for using this Microsoft social networking site). You seem to be just tagging. I think we can add an empty github action to just make a release for each "v[0-9]" tag...

just updated the build with your suggestions. Will see if I can add you there too so there's no delay if you want to do it yourself too.

*edit: instead of '--locked' i used '--frozen'... and thanks for catching the missing pkgdir thing!

**Comment by Troels51** [comment]
Thanks!
It was on my to-do list to automate the releases, now I  have an additional reason to do it

**Pull request merged**
